/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as BibliographyRouteImport } from './routes/bibliography'
import { Route as BioRouteImport } from './routes/bio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FameRouteImport } from './routes/fame'
import { Route as GearRouteImport } from './routes/gear'
import { Route as GuestbookRouteImport } from './routes/guestbook'
import { Route as HomeRouteImport } from './routes/home'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliographyRoute = BibliographyRouteImport.update({
  id: '/bibliography',
  path: '/bibliography',
  getParentRoute: () => rootRouteImport,
} as any)
const BioRoute = BioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FameRoute = FameRouteImport.update({
  id: '/fame',
  path: '/fame',
  getParentRoute: () => rootRouteImport,
} as any)
const GearRoute = GearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestbookRoute = GuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/bibliography': typeof BibliographyRoute
  '/bio': typeof BioRoute
  '/contact': typeof ContactRoute
  '/fame': typeof FameRoute
  '/gear': typeof GearRoute
  '/guestbook': typeof GuestbookRoute
  '/home': typeof HomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/bibliography': typeof BibliographyRoute
  '/bio': typeof BioRoute
  '/contact': typeof ContactRoute
  '/fame': typeof FameRoute
  '/gear': typeof GearRoute
  '/guestbook': typeof GuestbookRoute
  '/home': typeof HomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/bibliography': typeof BibliographyRoute
  '/bio': typeof BioRoute
  '/contact': typeof ContactRoute
  '/fame': typeof FameRoute
  '/gear': typeof GearRoute
  '/guestbook': typeof GuestbookRoute
  '/home': typeof HomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/bibliography'
    | '/bio'
    | '/contact'
    | '/fame'
    | '/gear'
    | '/guestbook'
    | '/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/bibliography'
    | '/bio'
    | '/contact'
    | '/fame'
    | '/gear'
    | '/guestbook'
    | '/home'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/bibliography'
    | '/bio'
    | '/contact'
    | '/fame'
    | '/gear'
    | '/guestbook'
    | '/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  BibliographyRoute: typeof BibliographyRoute
  BioRoute: typeof BioRoute
  ContactRoute: typeof ContactRoute
  FameRoute: typeof FameRoute
  GearRoute: typeof GearRoute
  GuestbookRoute: typeof GuestbookRoute
  HomeRoute: typeof HomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bibliography': {
      id: '/bibliography'
      path: '/bibliography'
      fullPath: '/bibliography'
      preLoaderRoute: typeof BibliographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio': {
      id: '/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof BioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fame': {
      id: '/fame'
      path: '/fame'
      fullPath: '/fame'
      preLoaderRoute: typeof FameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear': {
      id: '/gear'
      path: '/gear'
      fullPath: '/gear'
      preLoaderRoute: typeof GearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestbook': {
      id: '/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof GuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  BibliographyRoute: BibliographyRoute,
  BioRoute: BioRoute,
  ContactRoute: ContactRoute,
  FameRoute: FameRoute,
  GearRoute: GearRoute,
  GuestbookRoute: GuestbookRoute,
  HomeRoute: HomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
